# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09
Description: "ND9991 C3 L4"
Parameters:
  AmiToUse:
    Type: String
    Default: ami-006e00d6ac75d2ebb
    Description: Enter ami to create an instance base region
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
      - !Ref InstanceSecurityGroup
      # Change this, as applicable to you      
      KeyName: udacity
      # Change this, as applicable to you
      # You may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
      ImageId: !Ref AmiToUse 
      InstanceType: t3.micro
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '3000'
        ToPort: '3000'
        CidrIp: 0.0.0.0/0
        